# Generated by Django 4.1.7 on 2023-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_reservations_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
